//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSEye {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringDef {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringDef() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSEye.StringDef", typeof(StringDef).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 尝试配置Guard 的本地化字符串。
        /// </summary>
        internal static string AttemptToConfigGuard {
            get {
                return ResourceManager.GetString("AttemptToConfigGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份游戏数据库 的本地化字符串。
        /// </summary>
        internal static string BackupDatabaseAutomation {
            get {
                return ResourceManager.GetString("BackupDatabaseAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份游戏数据库。BackMode为0或1。为0时备份角色库，为1时备份日志库。 的本地化字符串。
        /// </summary>
        internal static string BackupDatabaseAutomationDes {
            get {
                return ResourceManager.GetString("BackupDatabaseAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份文件名 的本地化字符串。
        /// </summary>
        internal static string BackupFileName {
            get {
                return ResourceManager.GetString("BackupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份模式 的本地化字符串。
        /// </summary>
        internal static string BackupMode {
            get {
                return ResourceManager.GetString("BackupMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行批处理任务 的本地化字符串。
        /// </summary>
        internal static string BatchTaskAutomation {
            get {
                return ResourceManager.GetString("BatchTaskAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批处理任务名称 的本地化字符串。
        /// </summary>
        internal static string BatchTaskName {
            get {
                return ResourceManager.GetString("BatchTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定IP 的本地化字符串。
        /// </summary>
        internal static string BindIP {
            get {
                return ResourceManager.GetString("BindIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查服务器 的本地化字符串。
        /// </summary>
        internal static string CheckServerAutomation {
            get {
                return ResourceManager.GetString("CheckServerAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查类型 的本地化字符串。
        /// </summary>
        internal static string CheckType {
            get {
                return ResourceManager.GetString("CheckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建Lord配置文件 的本地化字符串。
        /// </summary>
        internal static string CreateLordConfigAutomation {
            get {
                return ResourceManager.GetString("CreateLordConfigAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建Lord配置文件任务。 的本地化字符串。
        /// </summary>
        internal static string CreateLordConfigAutomationDes {
            get {
                return ResourceManager.GetString("CreateLordConfigAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建服务器列表相关文件 的本地化字符串。
        /// </summary>
        internal static string CreateServerListFilesAutomation {
            get {
                return ResourceManager.GetString("CreateServerListFilesAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建服务器列表相关文件的任务，文件主要包括index.ini,index.ini.crc和state.ini，有一个参数，为文件目录。 的本地化字符串。
        /// </summary>
        internal static string CreateServerListFilesAutomationDes {
            get {
                return ResourceManager.GetString("CreateServerListFilesAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建服务器列表相关文件的任务，保存在配置文件SystemConfig.xml中的预设路径&quot;ServerListFileDir&quot;下，文件由预设文件名&quot;ServerListFileName&quot;和&quot;ServerListCRCFileName&quot;定义 的本地化字符串。
        /// </summary>
        internal static string CreateServerListFilesAutomationDesNew {
            get {
                return ResourceManager.GetString("CreateServerListFilesAutomationDesNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建服务器状态文件 的本地化字符串。
        /// </summary>
        internal static string CreateServerStateFileAutomation {
            get {
                return ResourceManager.GetString("CreateServerStateFileAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建服务器状态文件的任务，有一个参数，为文件目录。 的本地化字符串。
        /// </summary>
        internal static string CreateServerStateFileAutomationDes {
            get {
                return ResourceManager.GetString("CreateServerStateFileAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟时间(秒) 的本地化字符串。
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除FSEye本地文件 的本地化字符串。
        /// </summary>
        internal static string DeleteLocalFileAutomation {
            get {
                return ResourceManager.GetString("DeleteLocalFileAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除FSEye本地文件的任务，有一个参数为文件名。 的本地化字符串。
        /// </summary>
        internal static string DeleteLocalFileAutomationDes {
            get {
                return ResourceManager.GetString("DeleteLocalFileAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行系统命令 的本地化字符串。
        /// </summary>
        internal static string ExeSysCmdAutomation {
            get {
                return ResourceManager.GetString("ExeSysCmdAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行系统命令任务，参数是命令脚本。 的本地化字符串。
        /// </summary>
        internal static string ExeSysCmdAutomationDes {
            get {
                return ResourceManager.GetString("ExeSysCmdAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件目录 的本地化字符串。
        /// </summary>
        internal static string FileDir {
            get {
                return ResourceManager.GetString("FileDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件下载 的本地化字符串。
        /// </summary>
        internal static string FileDownloadAutomation {
            get {
                return ResourceManager.GetString("FileDownloadAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载文件任务，参数为Guard端文件的文件名(含路径)。 的本地化字符串。
        /// </summary>
        internal static string FileDownloadAutomationDes {
            get {
                return ResourceManager.GetString("FileDownloadAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输(上传)文件 的本地化字符串。
        /// </summary>
        internal static string FileTransferAutomation {
            get {
                return ResourceManager.GetString("FileTransferAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输(上传)文件任务，参数为FSEye目录下文件名且不含路径。 的本地化字符串。
        /// </summary>
        internal static string FileTransferAutomationDes {
            get {
                return ResourceManager.GetString("FileTransferAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤服务器 的本地化字符串。
        /// </summary>
        internal static string FilterServerAutomation {
            get {
                return ResourceManager.GetString("FilterServerAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤服务器任务，过滤掉上下文中的服务器。有两个参数，第一个参数为游戏状态，包括：Unknown,Stopped,Starting,Running,Stopping,Timeout,Dead和Restarting；第二个参数为服务器状态，包括：Unknown,Restarting,Running和Updating。状态之间用空格间隔。 的本地化字符串。
        /// </summary>
        internal static string FilterServerAutomationDes {
            get {
                return ResourceManager.GetString("FilterServerAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ftp更新服务器 的本地化字符串。
        /// </summary>
        internal static string FtpDownload {
            get {
                return ResourceManager.GetString("FtpDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP服务器编号 的本地化字符串。
        /// </summary>
        internal static string FtpServerId {
            get {
                return ResourceManager.GetString("FtpServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏服务器[{0}]的[{1}]模块发生错误，错误码是[{2}]。 的本地化字符串。
        /// </summary>
        internal static string GameModuleError {
            get {
                return ResourceManager.GetString("GameModuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏状态 的本地化字符串。
        /// </summary>
        internal static string GameState {
            get {
                return ResourceManager.GetString("GameState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当机堆栈 的本地化字符串。
        /// </summary>
        internal static string GetStackTraceAutomation {
            get {
                return ResourceManager.GetString("GetStackTraceAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当机堆栈任务。 的本地化字符串。
        /// </summary>
        internal static string GetStackTraceAutomationDes {
            get {
                return ResourceManager.GetString("GetStackTraceAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀掉游戏 的本地化字符串。
        /// </summary>
        internal static string KillGameAutomation {
            get {
                return ResourceManager.GetString("KillGameAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束游戏进程任务，彻底清除游戏进程，不保证游戏正常退出。 的本地化字符串。
        /// </summary>
        internal static string KillGameAutomationDes {
            get {
                return ResourceManager.GetString("KillGameAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录日志 的本地化字符串。
        /// </summary>
        internal static string LogAutomation {
            get {
                return ResourceManager.GetString("LogAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录日志任务。 的本地化字符串。
        /// </summary>
        internal static string LogAutomationDes {
            get {
                return ResourceManager.GetString("LogAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]向服务器[{1}]{2}发送GM指令[{3}][{4}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageExecuteGMCommand {
            get {
                return ResourceManager.GetString("LogMessageExecuteGMCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]向服务器[{1}]执行系统命令[{2}][{3}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageExecuteSystemCommand {
            get {
                return ResourceManager.GetString("LogMessageExecuteSystemCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]向服务器[{1}]发送获取游戏运行时间的指令[{2}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageGetGameRunningTime {
            get {
                return ResourceManager.GetString("LogMessageGetGameRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]向服务器[{1}]发送查看在线玩家的指令[{2}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageRefreshPlayerWho {
            get {
                return ResourceManager.GetString("LogMessageRefreshPlayerWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]向服务器[{1}]发送世界消息[{2}][{3}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageSayToWorld {
            get {
                return ResourceManager.GetString("LogMessageSayToWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]启动服务器[{1}]的游戏[{2}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageStartGame {
            get {
                return ResourceManager.GetString("LogMessageStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]启动了系统服务 的本地化字符串。
        /// </summary>
        internal static string LogMessageStartService {
            get {
                return ResourceManager.GetString("LogMessageStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]关闭服务器[{1}]的游戏[{2}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageStopGame {
            get {
                return ResourceManager.GetString("LogMessageStopGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]关闭了系统服务 的本地化字符串。
        /// </summary>
        internal static string LogMessageStopService {
            get {
                return ResourceManager.GetString("LogMessageStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]对服务器[{1}]进行游戏更新[{2}] 的本地化字符串。
        /// </summary>
        internal static string LogMessageUpdateGame {
            get {
                return ResourceManager.GetString("LogMessageUpdateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件内容 的本地化字符串。
        /// </summary>
        internal static string MailContent {
            get {
                return ResourceManager.GetString("MailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息内容 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空自动化作业 的本地化字符串。
        /// </summary>
        internal static string NullAutomation {
            get {
                return ResourceManager.GetString("NullAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空自动化任务，一般做为测试用。 的本地化字符串。
        /// </summary>
        internal static string NullAutomationDes {
            get {
                return ResourceManager.GetString("NullAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新包名 的本地化字符串。
        /// </summary>
        internal static string PatchName {
            get {
                return ResourceManager.GetString("PatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码(用&quot;;&quot;分隔) 的本地化字符串。
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人 的本地化字符串。
        /// </summary>
        internal static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回滚游戏数据库 的本地化字符串。
        /// </summary>
        internal static string RollbackDatabaseAutomation {
            get {
                return ResourceManager.GetString("RollbackDatabaseAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回滚游戏数据库。参数是数据库备份文件名。 的本地化字符串。
        /// </summary>
        internal static string RollbackDatabaseAutomationDes {
            get {
                return ResourceManager.GetString("RollbackDatabaseAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本内容 的本地化字符串。
        /// </summary>
        internal static string ScriptText {
            get {
                return ResourceManager.GetString("ScriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择服务器 的本地化字符串。
        /// </summary>
        internal static string SelectServerAutomation {
            get {
                return ResourceManager.GetString("SelectServerAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发邮件 的本地化字符串。
        /// </summary>
        internal static string SendMailAutomation {
            get {
                return ResourceManager.GetString("SendMailAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发邮件任务，有三个参数，第一个为收件人的E-Mail地址，多个地址用空格隔开；第二个为邮件主题；第三个为邮件内容（可多选）。 的本地化字符串。
        /// </summary>
        internal static string SendMailAutomationDes {
            get {
                return ResourceManager.GetString("SendMailAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送短信 的本地化字符串。
        /// </summary>
        internal static string SendSMSAutomation {
            get {
                return ResourceManager.GetString("SendSMSAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过公司内部短信网关发送短信 的本地化字符串。
        /// </summary>
        internal static string SendSMSAutomationDes {
            get {
                return ResourceManager.GetString("SendSMSAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送系统消息 的本地化字符串。
        /// </summary>
        internal static string SendSystemMessageAutomation {
            get {
                return ResourceManager.GetString("SendSystemMessageAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送系统消息任务，有一个参数，为消息内容。 的本地化字符串。
        /// </summary>
        internal static string SendSystemMessageAutomationDes {
            get {
                return ResourceManager.GetString("SendSystemMessageAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新开 的本地化字符串。
        /// </summary>
        internal static string ServerFlagNew {
            get {
                return ResourceManager.GetString("ServerFlagNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        internal static string ServerFlagRecommend {
            get {
                return ResourceManager.GetString("ServerFlagRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器组ID 的本地化字符串。
        /// </summary>
        internal static string ServerGroupId {
            get {
                return ResourceManager.GetString("ServerGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器ID 的本地化字符串。
        /// </summary>
        internal static string ServerId {
            get {
                return ResourceManager.GetString("ServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态 的本地化字符串。
        /// </summary>
        internal static string ServerState {
            get {
                return ResourceManager.GetString("ServerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信内容 的本地化字符串。
        /// </summary>
        internal static string SmsContent {
            get {
                return ResourceManager.GetString("SmsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始配置Guard 的本地化字符串。
        /// </summary>
        internal static string StartConfigGuard {
            get {
                return ResourceManager.GetString("StartConfigGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        internal static string StartGameAutomation {
            get {
                return ResourceManager.GetString("StartGameAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏任务，参数为服务器或者服务器组，从上下文中获得。 的本地化字符串。
        /// </summary>
        internal static string StartGameAutomationDes {
            get {
                return ResourceManager.GetString("StartGameAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏失败 的本地化字符串。
        /// </summary>
        internal static string StartGameFailed {
            get {
                return ResourceManager.GetString("StartGameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁忙 的本地化字符串。
        /// </summary>
        internal static string StateBusy {
            get {
                return ResourceManager.GetString("StateBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爆满 的本地化字符串。
        /// </summary>
        internal static string StateFull {
            get {
                return ResourceManager.GetString("StateFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 良好 的本地化字符串。
        /// </summary>
        internal static string StateGood {
            get {
                return ResourceManager.GetString("StateGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护 的本地化字符串。
        /// </summary>
        internal static string StateStoped {
            get {
                return ResourceManager.GetString("StateStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string StateUnknow {
            get {
                return ResourceManager.GetString("StateUnknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止配置Guard 的本地化字符串。
        /// </summary>
        internal static string StopConfigGuard {
            get {
                return ResourceManager.GetString("StopConfigGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭游戏 的本地化字符串。
        /// </summary>
        internal static string StopGameAutomation {
            get {
                return ResourceManager.GetString("StopGameAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭游戏任务，有两个参数，一个是延迟关闭的时间，单位为秒；第二个参数为世界消息。 的本地化字符串。
        /// </summary>
        internal static string StopGameAutomationDes {
            get {
                return ResourceManager.GetString("StopGameAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭游戏失败 的本地化字符串。
        /// </summary>
        internal static string StopGameFailed {
            get {
                return ResourceManager.GetString("StopGameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换Guard模式 的本地化字符串。
        /// </summary>
        internal static string SwitchGuardMode {
            get {
                return ResourceManager.GetString("SwitchGuardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新游戏 的本地化字符串。
        /// </summary>
        internal static string UpdateGameAutomation {
            get {
                return ResourceManager.GetString("UpdateGameAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新游戏任务，有一个参数，为更新包的名称。 的本地化字符串。
        /// </summary>
        internal static string UpdateGameAutomationDes {
            get {
                return ResourceManager.GetString("UpdateGameAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传服务器列表相关文件到FTP 的本地化字符串。
        /// </summary>
        internal static string UploadServerListFilesToFtpAutomation {
            get {
                return ResourceManager.GetString("UploadServerListFilesToFtpAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传服务器列表相关文件到FTP的任务，有两个参数，第一个为FTP服务器的编号，多个FTP编号用空格隔开；第二个为单个FTP连接的超时时间，单位为秒，若不填则为5分钟 的本地化字符串。
        /// </summary>
        internal static string UploadServerListFilesToFtpAutomationDes {
            get {
                return ResourceManager.GetString("UploadServerListFilesToFtpAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待 的本地化字符串。
        /// </summary>
        internal static string WaitAutomation {
            get {
                return ResourceManager.GetString("WaitAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待任务，有一个参数，为等待的秒数。 的本地化字符串。
        /// </summary>
        internal static string WaitAutomationDes {
            get {
                return ResourceManager.GetString("WaitAutomationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待时间(秒) 的本地化字符串。
        /// </summary>
        internal static string WaitTime {
            get {
                return ResourceManager.GetString("WaitTime", resourceCulture);
            }
        }
    }
}
