using System;
using System.Collections.Generic;
using System.Text;

namespace JX2Lib
{
    public enum JxRoleType
    {   
        Wumenpai=0,
        Shaolin = 1,
        ShaolinWuluxian = 100,
        Daoshaolin = 101,
        Gunshaolin = 102,
        Tianwang = 2,
        TianwangWuluxian = 200,
        Qiantianwang = 201,
        Cuitianwang = 202,
        Tangmen = 3,
        TangmenWuluxian = 300,
        Xianjintangmen = 301,
        Xiujiantangmen = 302,
        Wudu = 4,
        WuduWuluxian = 400,
        Daowudu = 401,
        Zhangwudu = 402,
        Emei = 5,
        EmeiWuluxian = 500,
        Zhangemei = 501,
        Fuzhuemei = 502,
        Cuiyan = 6,
        CuiyanWuluxian = 600,
        Jiancuiyan = 601,
        Daocuiyan = 602,
        Gaibang = 7,
        GaibangWuluxian = 700,
        Zhanggaibang = 701,
        Gungaibang = 702,
        Tianren = 8,
        TianrenWuluxian = 800,
        Zhangtianren = 801,
        Motianren = 802,
        Wudang = 9,
        WudangWuluxian = 900,
        Qiwudang = 901,
        Jianwudang = 902,
        Kunlun = 10,
        KunlunWuluxian = 1000,
        Daokunlun = 1001,
        Jiankunlun = 1002,
        Mingjiao = 11,
        MingjiaoWuluxian = 1100,
        Cuimingjiao = 1101,
        Jianmingjiao = 1102,
        Daliduanshi = 12,
        DaliduanshiWuluxian = 1200,
        Zhiduanshi = 1201,
        Qiduanshi = 1202,
    }
}
