// File: DisableWarns.h
// Desc; 屏蔽某些无用的警告信息

#ifndef DISABLEWARNS_H
#define DISABLEWARNS_H

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4786)

// disable: "conversion from 'double' to 'float', possible loss of data
#pragma warning (disable : 4244)

// disable: "truncation from 'double' to 'float'
#pragma warning (disable : 4305)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#pragma warning (disable : 4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#pragma warning (disable : 4275)

#pragma warning (disable : 4800)

#pragma warning (disable : 4018)  // disable warn "signed/unsigned mismatch"

#endif