#if !defined(AFX__FRMFRAME_H__6F8BCF0D_4713_4B43_93B6_12BDA782728E__INCLUDED_)
#define AFX__FRMFRAME_H__6F8BCF0D_4713_4B43_93B6_12BDA782728E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_frmFrame wrapper class
namespace MFCFramework
{

class C_frmFrame : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_frmFrame)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5bbfcb3b, 0x74cc, 0x49f5, { 0xb0, 0xab, 0x3c, 0xc9, 0x10, 0x7b, 0xaf, 0xcb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetEnabled();
	void SetEnabled(LPCTSTR lpszNewValue);
	CString GetPHeightMapName();
	void SetPHeightMapName(LPCTSTR lpszNewValue);
	BOOL MeLoadPictures();
	short GetPMaterialUp();
	void SetPMaterialUp(short nNewValue);
	short GetPMaterialDown();
	void SetPMaterialDown(short nNewValue);
	void LoadPictures();
	CString GetPTextureDir();
	void SetPTextureDir(LPCTSTR lpszNewValue);
	CString GetPTextureDefFile();
	void SetPTextureDefFile(LPCTSTR lpszNewValue);
	short GetPNumMaterial();
	void SetPNumMaterial(short nNewValue);
};
};
//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__FRMFRAME_H__6F8BCF0D_4713_4B43_93B6_12BDA782728E__INCLUDED_)
