// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "animationseekbar1.h"

/////////////////////////////////////////////////////////////////////////////
// CAnimationseekbar1

IMPLEMENT_DYNCREATE(CAnimationseekbar1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAnimationseekbar1 properties

/////////////////////////////////////////////////////////////////////////////
// CAnimationseekbar1 operations
