#pragma once

template <class T>
class CProxy_IGameEvents : public IConnectionPointImpl<T, &__uuidof( _IGameEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
