#ifndef KMISSILEREPRESENTMISSILEDEFINE_H
#define KMISSILEREPRESENTMISSILEDEFINE_H

enum RL_MISSILE_PHASE
{
    RL_MISSILE_PHASE_INFLIGHT,
    RL_MISSILE_PHASE_END_HIT,
    RL_MISSILE_PHASE_END_MISS,

    RL_MISSILE_PHASE_COUNT,
};

#endif // KMISSILEREPRESENTMISSILEDEFINE_H
