#pragma once

template <class T>
class CProxy_ITest3DEngineEvents : public IConnectionPointImpl<T, &__uuidof( _ITest3DEngineEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
