//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowChartEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowChartEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] actionNode_activated {
            get {
                object obj = ResourceManager.GetObject("actionNode_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] actionNode_disable_activated {
            get {
                object obj = ResourceManager.GetObject("actionNode_disable_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] actionNode_disable_normal {
            get {
                object obj = ResourceManager.GetObject("actionNode_disable_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] actionNode_disable_selected {
            get {
                object obj = ResourceManager.GetObject("actionNode_disable_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] actionNode_disable_shadow {
            get {
                object obj = ResourceManager.GetObject("actionNode_disable_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] actionNode_normal {
            get {
                object obj = ResourceManager.GetObject("actionNode_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] actionNode_selected {
            get {
                object obj = ResourceManager.GetObject("actionNode_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] actionNode_shadow {
            get {
                object obj = ResourceManager.GetObject("actionNode_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] addButton_activated {
            get {
                object obj = ResourceManager.GetObject("addButton_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] addButton_normal {
            get {
                object obj = ResourceManager.GetObject("addButton_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionNode_activated {
            get {
                object obj = ResourceManager.GetObject("aiActionNode_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionNode_normal {
            get {
                object obj = ResourceManager.GetObject("aiActionNode_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionNode_selected {
            get {
                object obj = ResourceManager.GetObject("aiActionNode_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionNode_shadow {
            get {
                object obj = ResourceManager.GetObject("aiActionNode_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionsNode_activated {
            get {
                object obj = ResourceManager.GetObject("aiActionsNode_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionsNode_normal {
            get {
                object obj = ResourceManager.GetObject("aiActionsNode_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionsNode_selected {
            get {
                object obj = ResourceManager.GetObject("aiActionsNode_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiActionsNode_shadow {
            get {
                object obj = ResourceManager.GetObject("aiActionsNode_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiStateNode_activated {
            get {
                object obj = ResourceManager.GetObject("aiStateNode_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiStateNode_normal {
            get {
                object obj = ResourceManager.GetObject("aiStateNode_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiStateNode_selected {
            get {
                object obj = ResourceManager.GetObject("aiStateNode_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] aiStateNode_shadow {
            get {
                object obj = ResourceManager.GetObject("aiStateNode_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_activated {
            get {
                object obj = ResourceManager.GetObject("conditionNode_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_disable_activated {
            get {
                object obj = ResourceManager.GetObject("conditionNode_disable_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_disable_normal {
            get {
                object obj = ResourceManager.GetObject("conditionNode_disable_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_disable_selected {
            get {
                object obj = ResourceManager.GetObject("conditionNode_disable_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_disable_shadow {
            get {
                object obj = ResourceManager.GetObject("conditionNode_disable_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_normal {
            get {
                object obj = ResourceManager.GetObject("conditionNode_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_selected {
            get {
                object obj = ResourceManager.GetObject("conditionNode_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] conditionNode_shadow {
            get {
                object obj = ResourceManager.GetObject("conditionNode_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] connectButton_activated {
            get {
                object obj = ResourceManager.GetObject("connectButton_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] connectButton_normal {
            get {
                object obj = ResourceManager.GetObject("connectButton_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_activated {
            get {
                object obj = ResourceManager.GetObject("eventNode_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_disable_activated {
            get {
                object obj = ResourceManager.GetObject("eventNode_disable_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_disable_normal {
            get {
                object obj = ResourceManager.GetObject("eventNode_disable_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_disable_selected {
            get {
                object obj = ResourceManager.GetObject("eventNode_disable_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_disable_shadow {
            get {
                object obj = ResourceManager.GetObject("eventNode_disable_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_normal {
            get {
                object obj = ResourceManager.GetObject("eventNode_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_selected {
            get {
                object obj = ResourceManager.GetObject("eventNode_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] eventNode_shadow {
            get {
                object obj = ResourceManager.GetObject("eventNode_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] interfaceNode_activated {
            get {
                object obj = ResourceManager.GetObject("interfaceNode_activated", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] interfaceNode_normal {
            get {
                object obj = ResourceManager.GetObject("interfaceNode_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] interfaceNode_selected {
            get {
                object obj = ResourceManager.GetObject("interfaceNode_selected", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] interfaceNode_shadow {
            get {
                object obj = ResourceManager.GetObject("interfaceNode_shadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scrollArraw_down {
            get {
                object obj = ResourceManager.GetObject("scrollArraw_down", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scrollArraw_left {
            get {
                object obj = ResourceManager.GetObject("scrollArraw_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scrollArraw_right {
            get {
                object obj = ResourceManager.GetObject("scrollArraw_right", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scrollArraw_up {
            get {
                object obj = ResourceManager.GetObject("scrollArraw_up", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
