// MeshMdlExt.idl : IDL source for MeshMdlExt
//

// This file will be processed by the MIDL tool to
// produce the type library (MeshMdlExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(51BD6BAE-9464-4D9C-B614-32D2615287A7),
	helpstring("IMeshMdlShlExt Interface"),
	pointer_default(unique)
]
interface IMeshMdlShlExt : IUnknown{
};
[
	uuid(5ABF40F5-53F6-4B75-81B4-7C55C83603DE),
	version(1.0),
	helpstring("MeshMdlExt 1.0 Type Library")
]
library MeshMdlExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(F2F594C3-33F2-47D1-B035-61F88F803033),
		helpstring("MeshMdlShlExt Class")
	]
	coclass MeshMdlShlExt
	{
		[default] interface IMeshMdlShlExt;
	};
};
